//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.19 at 01:36:37 PM CEST
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="loanAmount">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="100"/>
 *               &lt;maxInclusive value="100000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="loanAmountToPayback" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dueDays">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="5"/>
 *               &lt;maxInclusive value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="paidBack" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *       &lt;attribute name="loanId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "loanAmount",
        "loanAmountToPayback",
        "dueDays",
        "paidBack"
})
@XmlRootElement(name = "loan")
public class Loan {

    protected int loanAmount;
    protected int loanAmountToPayback;
    protected int dueDays;
    protected boolean paidBack;
    @XmlAttribute(name = "loanId", required = true)
    protected int loanId;

    /**
     * Gets the value of the loanAmount property.
     *
     */

    public boolean getPaidBack(){return paidBack;}
    public int getLoanAmount() {
        return loanAmount;
    }

    /**
     * Sets the value of the loanAmount property.
     *
     */
    public void setLoanAmount(int value) {
        this.loanAmount = value;
    }

    /**
     * Gets the value of the loanAmountToPayback property.
     *
     */
    public int getLoanAmountToPayback() {
        return loanAmountToPayback;
    }

    /**
     * Sets the value of the loanAmountToPayback property.
     *
     */
    public void setLoanAmountToPayback(int value) {
        this.loanAmountToPayback = value;
    }

    /**
     * Gets the value of the dueDays property.
     *
     */
    public int getDueDays() {
        return dueDays;
    }

    /**
     * Sets the value of the dueDays property.
     *
     */
    public void setDueDays(int value) {
        this.dueDays = value;
    }

    /**
     * Gets the value of the paidBack property.
     *
     */
    public boolean isPaidBack() {
        return paidBack;
    }

    /**
     * Sets the value of the paidBack property.
     *
     */
    public void setPaidBack(boolean value) {
        this.paidBack = value;
    }

    /**
     * Gets the value of the loanId property.
     *
     */
    public int getLoanId() {
        return loanId;
    }

    /**
     * Sets the value of the loanId property.
     *
     */
    public void setLoanId(int value) {
        this.loanId = value;
    }

}
